
const icons={
 bell:`<svg viewBox="0 0 24 24"><path d="M15 17h5l-1.4-1.4A2 2 0 0 1 18 14.2V11a6 6 0 1 0-12 0v3.2a2 2 0 0 1-.6 1.4L4 17h5"></path><path d="M10 21a2 2 0 0 0 4 0"></path></svg>`,
 check:`<svg viewBox="0 0 24 24"><path d="m5 12 4 4 10-10"></path></svg>`,
 book:`<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5z"></path><path d="M4 5.5v16"></path></svg>`,
 trend:`<svg viewBox="0 0 24 24"><path d="M4 19V5"></path><path d="M4 19h16"></path><path d="m7 15 4-4 3 3 5-7"></path></svg>`,
 map:`<svg viewBox="0 0 24 24"><path d="m4 6 5-2 6 2 5-2v14l-5 2-6-2-5 2z"></path><path d="M9 4v14"></path><path d="M15 6v14"></path></svg>`,
 message:`<svg viewBox="0 0 24 24"><path d="M4 5h16v11H8l-4 4z"></path><path d="M8 9h8"></path><path d="M8 12h5"></path></svg>`,
 search:`<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>`,
 scan:`<svg viewBox="0 0 24 24"><path d="M4 8V5a1 1 0 0 1 1-1h3"></path><path d="M20 8V5a1 1 0 0 0-1-1h-3"></path><path d="M4 16v3a1 1 0 0 0 1 1h3"></path><path d="M20 16v3a1 1 0 0 1-1 1h-3"></path><path d="M7 12h10"></path><path d="M8 9.5h1"></path><path d="M8 14.5h1"></path><path d="M11 9.5h1"></path><path d="M11 14.5h1"></path><path d="M14 9.5h1"></path><path d="M17 9.5h1"></path><path d="M14 14.5h4"></path></svg>`,
 back:`<svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"></path></svg>`,
 more:`<svg viewBox="0 0 24 24"><circle cx="6" cy="12" r="1.4"></circle><circle cx="12" cy="12" r="1.4"></circle><circle cx="18" cy="12" r="1.4"></circle></svg>`,
 play:`<svg viewBox="0 0 24 24"><path d="m9 7 8 5-8 5z"></path></svg>`,
 home:`<svg viewBox="0 0 24 24"><path d="M4 10.5 12 4l8 6.5"></path><path d="M6.5 9.5V20h11V9.5"></path></svg>`,
 list:`<svg viewBox="0 0 24 24"><path d="M7 6h13"></path><path d="M7 12h13"></path><path d="M7 18h13"></path><path d="M4 6h.01"></path><path d="M4 12h.01"></path><path d="M4 18h.01"></path></svg>`,
 cart:`<svg viewBox="0 0 24 24"><path d="M5 5h2l2 10h9l2-7H8"></path><circle cx="10" cy="19" r="1.5"></circle><circle cx="18" cy="19" r="1.5"></circle></svg>`,
 user:`<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"></circle><path d="M5 20a7 7 0 0 1 14 0"></path></svg>`,
 accessibility:`<svg viewBox="0 0 24 24"><circle cx="12" cy="4" r="1.5"></circle><path d="M5 8h14"></path><path d="M12 8v12"></path><path d="m8 20 4-7 4 7"></path></svg>`,
 info:`<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M12 10v6"></path><path d="M12 7h.01"></path></svg>`,
 shield:`<svg viewBox="0 0 24 24"><path d="M12 3 5 6v5c0 4.5 2.8 8 7 10 4.2-2 7-5.5 7-10V6z"></path></svg>`,
 file:`<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6z"></path><path d="M14 3v4h4"></path><path d="M9 12h6"></path><path d="M9 16h6"></path></svg>`,
 phone:`<svg viewBox="0 0 24 24"><path d="M6 3h4l2 5-3 2a15 15 0 0 0 5 5l2-3 5 2v4a3 3 0 0 1-3 3C9.7 21 3 14.3 3 6a3 3 0 0 1 3-3z"></path></svg>`,
 mail:`<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"></path><path d="m4 7 8 6 8-6"></path></svg>`,
 pin:`<svg viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0z"></path><circle cx="12" cy="10" r="2.5"></circle></svg>`,
 clock:`<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path></svg>`,
 orthotic:`<svg viewBox="0 0 24 24"><path d="M7 4c4 0 7 5 7 9 0 4-2 7-5 7-3 0-4-2-4-5 0-4 2-7 2-11z"></path></svg>`,
 support:`<svg viewBox="0 0 24 24"><path d="M6 4h12v16H6z"></path><path d="M9 8h6"></path><path d="M9 12h6"></path></svg>`,
 care:`<svg viewBox="0 0 24 24"><path d="M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10z"></path></svg>`,
 tape:`<svg viewBox="0 0 24 24"><path d="m5 8 3-3 11 11-3 3z"></path><path d="m8 5 3-3 11 11-3 3"></path></svg>`,
 sparkles:`<svg viewBox="0 0 24 24"><path d="M12 3l1.2 3.3L16.5 7.5l-3.3 1.2L12 12l-1.2-3.3L7.5 7.5l3.3-1.2L12 3z"></path><path d="M5 13l.8 2.2L8 16l-2.2.8L5 19l-.8-2.2L2 16l2.2-.8L5 13z"></path><path d="M19 11l.8 2.2L22 14l-2.2.8L19 17l-.8-2.2L16 14l2.2-.8L19 11z"></path></svg>`,
 close:`<svg viewBox="0 0 24 24"><path d="M6 6l12 12"></path><path d="M18 6L6 18"></path></svg>`,
 logout:`<svg viewBox="0 0 24 24"><path d="M10 5H5v14h5"></path><path d="M14 8l4 4-4 4"></path><path d="M18 12H9"></path></svg>`
};
for(const [name,svg] of Object.entries(icons)){document.body.innerHTML=document.body.innerHTML.replaceAll(`{{${name}}}`,svg)}


const fmtVideoModal=document.getElementById('fmtVideoModal');
const openFmtVideo=document.getElementById('openFmtVideo');
const closeFmtVideo=document.getElementById('closeFmtVideo');
if(openFmtVideo&&fmtVideoModal){openFmtVideo.addEventListener('click',()=>{fmtVideoModal.classList.add('open');fmtVideoModal.setAttribute('aria-hidden','false')})}
if(closeFmtVideo&&fmtVideoModal){closeFmtVideo.addEventListener('click',()=>{fmtVideoModal.classList.remove('open');fmtVideoModal.setAttribute('aria-hidden','true')})}
if(fmtVideoModal){fmtVideoModal.addEventListener('click',e=>{if(e.target===fmtVideoModal){fmtVideoModal.classList.remove('open');fmtVideoModal.setAttribute('aria-hidden','true')}})}

const resources=[
{id:'tennis-ball-roll',title:'Tennis Ball Roll',type:'exercise',area:'foot',image:'exercise-tennis.png',description:'Helps release tension through the muscles under the foot and improve comfortable movement.',sets:'1 set',reps:'1 minute',frequency:'3× daily'},
{id:'calf-stretch',title:'Calf Stretch',type:'exercise',area:'lower leg',image:'intro-beach.png',description:'Support calf flexibility and comfortable movement.',sets:'2 sets',reps:'30 seconds',frequency:'Daily'},
{id:'ankle-strength',title:'Ankle Strength',type:'exercise',area:'ankle',image:'resource-ankle.png',description:'Build ankle strength and control.',sets:'2 sets',reps:'15 reps',frequency:'3× weekly'},
{id:'metatarsal-dome',title:'Metatarsal Dome Placement',type:'guide',area:'foot',image:'resource-guide.png',description:'How and where to place metatarsal domes safely.',sets:'Guide',reps:'Placement',frequency:'As advised'},
{id:'needling-aftercare',title:'Needling Information and Aftercare',type:'aftercare',area:'general',image:'intro-patient.png',description:'Aftercare guidance following your needling session.',sets:'Guide',reps:'Aftercare',frequency:'As needed'},
{id:'strapping-information',title:'Strapping Information',type:'guide',area:'general',image:'resource-guide.png',description:'Helpful information about looking after your strapping.',sets:'Guide',reps:'Reference',frequency:'As needed'},
{id:'contrast-bath',title:'Contrast Bath Technique',type:'aftercare',area:'foot',image:'resource-foot.png',description:'Simple step-by-step guidance for contrast bath technique.',sets:'Guide',reps:'Technique',frequency:'As advised'},
{id:'plantar-fascia-release',title:'Plantar Fascia Release',type:'exercise',area:'foot',image:'exercise-tennis.png',description:'Reduce tension and support better movement.',sets:'1 set',reps:'90 seconds',frequency:'1–2× daily'},
{id:'big-toe-mobility',title:'Big Toe Mobilization',type:'exercise',area:'foot',image:'resource-foot.png',description:'Improve big toe motion and support walking comfort.',sets:'2 sets',reps:'10 reps',frequency:'Daily'}];
const saved=new Set(JSON.parse(localStorage.getItem('stridePrescribedResources')||'[]'));let activeTab='prescribed',activeFilter='all',currentResource=resources[0],currentResourceSource='prescribed',entryTotal=8;
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'instant'});if(id==='resources'){renderMyResources();renderLibrary()}}
document.querySelectorAll('.go').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));
function resourceMarkup(r,source='library'){return `<button class="resource-card card open-resource" data-id="${r.id}" data-source="${source}"><img src="${r.image}" alt="${r.title}"><div><h3>${r.title}</h3><p>${r.type==='exercise'?'Prescribed Exercise':r.type==='aftercare'?'Aftercare Guide':'Information Guide'}</p><div class="resource-meta">${r.frequency}</div><span class="resource-badge ${r.area.replace(/\s+/g,'-')}">${r.area}</span></div><span class="chevron">›</span></button>`}
function bindResourceButtons(){document.querySelectorAll('.open-resource').forEach(b=>b.addEventListener('click',()=>openResource(b.dataset.id,b.dataset.source||'library')))}
function renderMyResources(){const items=resources.filter(r=>saved.has(r.id));document.getElementById('myResourceList').innerHTML=items.length?items.map(r=>resourceMarkup(r,'prescribed')).join(''):`<div class="card" style="margin:14px 18px 0;padding:18px"><strong style="display:block;margin-bottom:6px;font-size:14px">No prescribed resources yet</strong><p style="margin:0;color:var(--muted);font-size:12.5px;line-height:1.5">Scan a QR code from your podiatrist to add your prescribed exercises and information guides.</p></div>`;bindResourceButtons()}
function renderLibrary(){const q=document.getElementById('resourceSearch').value.toLowerCase().trim();const items=resources.filter(r=>(activeFilter==='all'||r.type===activeFilter||r.area===activeFilter)&&(!q||r.title.toLowerCase().includes(q)||r.description.toLowerCase().includes(q)));document.getElementById('libraryList').innerHTML=items.map(r=>resourceMarkup(r,'library')).join('');bindResourceButtons()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('prescribedPanel').classList.toggle('active',activeTab==='prescribed');document.getElementById('libraryPanel').classList.toggle('active',activeTab==='library');if(activeTab==='prescribed')renderMyResources();else renderLibrary()}));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderLibrary()}));
document.getElementById('resourceSearch').addEventListener('input',renderLibrary);const categorySelect=document.getElementById('categorySelect');if(categorySelect){categorySelect.addEventListener('change',()=>{activeFilter=categorySelect.value;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderLibrary()})}
function openResource(id,source='library'){currentResource=resources.find(r=>r.id===id)||resources[0];currentResourceSource=source;detailImage.src=currentResource.image;detailTitle.textContent=currentResource.title;detailTag.textContent=currentResource.type==='exercise'?'Prescribed Exercise':currentResource.type==='aftercare'?'Aftercare Guide':'Information Guide';detailDescription.textContent=currentResource.description;doseSets.textContent=currentResource.sets;doseReps.textContent=currentResource.reps;doseFrequency.textContent=currentResource.frequency;setsInput.value=currentResource.sets;repsInput.value=currentResource.reps;frequencyInput.value=currentResource.frequency;saveResource.textContent=currentResourceSource==='library'?'Back to Library':(saved.has(currentResource.id)?'Update Prescribed Resource':'Update Prescribed Resource');showScreen('detail')}
document.getElementById('saveResource').addEventListener('click',()=>{if(currentResourceSource==='library'){showScreen('resources');activeTab='library';document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab==='library'));document.getElementById('prescribedPanel').classList.remove('active');document.getElementById('libraryPanel').classList.add('active');renderLibrary();return;}currentResource.sets=setsInput.value;currentResource.reps=repsInput.value;currentResource.frequency=frequencyInput.value;doseSets.textContent=currentResource.sets;doseReps.textContent=currentResource.reps;doseFrequency.textContent=currentResource.frequency;saveResource.textContent='Prescribed Resource Updated'});

const modal=document.getElementById('progressModal');
const openProgressModal=()=>modal.classList.add('open');
newEntry.addEventListener('click',openProgressModal);
newEntryTop.addEventListener('click',openProgressModal);
document.querySelector('.close-progress').addEventListener('click',()=>modal.classList.remove('open'));document.querySelector('.close-progress').addEventListener('touchend',e=>{e.preventDefault();modal.classList.remove('open')},{passive:false});
modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
let selectedPain=5,selectedImprovement=40;
document.querySelectorAll('#painChoices .number-choice').forEach(b=>b.addEventListener('click',()=>{selectedPain=Number(b.dataset.value);document.querySelectorAll('#painChoices .number-choice').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelectorAll('#improvementChoices .percent-choice').forEach(b=>b.addEventListener('click',()=>{selectedImprovement=Number(b.dataset.value);document.querySelectorAll('#improvementChoices .percent-choice').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelectorAll('[data-group]').forEach(group=>group.querySelectorAll('.pill-choice').forEach(b=>b.addEventListener('click',()=>group.querySelectorAll('.pill-choice').forEach(x=>x.classList.toggle('selected',x===b)))));
document.querySelector('#painChoices [data-value="5"]').classList.add('selected');
document.querySelector('#improvementChoices [data-value="40"]').classList.add('selected');
function selectedValue(group){return document.querySelector(`[data-group="${group}"] .selected`)?.dataset.value||''}
let latestCheckin={pain:5,morning:'Better',walking:'Better',shoes:'Same',flare:'No',consistency:'Mostly',improvement:40,better:'Morning stiffness has reduced and walking is more comfortable.',limited:'Stairs remain uncomfortable.'};
saveEntry.addEventListener('click',()=>{const morning=selectedValue('morning'),walking=selectedValue('walking'),shoes=selectedValue('shoes'),flare=selectedValue('flare'),consistency=selectedValue('consistency'),better=betterInput.value.trim(),limited=limitedInput.value.trim();entryTotal++;latestCheckin={pain:selectedPain,morning,walking,shoes,flare,consistency,improvement:selectedImprovement,better,limited};const date=new Date().toLocaleDateString('en-NZ',{day:'numeric',month:'long',year:'numeric'});const cls=v=>v==='Same'?'same':v==='Worse'?'worse':'';const card=document.createElement('div');card.className='history-card card';card.innerHTML=`<div class="history-top"><span class="history-date"><strong>${date}</strong></span><span class="pain-pill">Pain ${selectedPain}/10</span></div><div class="history-metrics"><div class="history-metric"><span>Morning</span><strong class="${cls(morning)}">${morning}</strong></div><div class="history-metric"><span>Walking</span><strong class="${cls(walking)}">${walking}</strong></div><div class="history-metric"><span>Shoes</span><strong class="${cls(shoes)}">${shoes}</strong></div></div>${better?`<div class="history-line"><strong>Better:</strong> ${better}</div>`:''}${limited?`<div class="history-line"><strong>Still limited:</strong> ${limited}</div>`:''}`;checkinHistory.prepend(card);betterInput.value='';limitedInput.value='';modal.classList.remove('open');updateSummaryModal()});if(window.copySummary&&window.podSummaryText){copySummary.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(podSummaryText.textContent);copySummary.textContent='Copied';setTimeout(()=>copySummary.textContent='Copy Summary',1500)}catch(e){alert(podSummaryText.textContent)}});}
if(window.shareSummary&&window.podSummaryText){shareSummary.addEventListener('click',async()=>{const txt=podSummaryText.textContent;if(navigator.share){try{await navigator.share({title:'Stride Progress Summary',text:txt})}catch(e){}}else{try{await navigator.clipboard.writeText(txt);alert('Progress summary copied.')}catch(e){alert(txt)}}});}


const summaryModal=document.getElementById('summaryModal');
function updateSummaryModal(){const c=latestCheckin;summaryLatestPain.textContent=`${c.pain}/10`;summaryImprovement.textContent=`${c.improvement}%`;summaryConsistency.textContent=c.consistency;const widths={Always:100,Mostly:82,Sometimes:55,Rarely:25};summaryConsistencyBar.style.width=(widths[c.consistency]||60)+'%';summaryConsistencyNote.textContent=c.consistency==='Always'?'Excellent consistency — you are completing your exercises very regularly.':c.consistency==='Mostly'?'You have been consistent with most prescribed exercises. Keep building on this routine.':c.consistency==='Sometimes'?'You are completing some exercises. A more regular routine may help support progress.':'Exercise consistency has been limited. Discuss any barriers with your podiatrist.';const readable=v=>v==='Better'?'Improving':v==='Worse'?'More limited':'About the same';summaryMorning.textContent=readable(c.morning);summaryWalking.textContent=readable(c.walking);summaryShoes.textContent=readable(c.shoes);summaryFlares.textContent=c.flare==='Yes'?'Flare-ups reported':'None reported';summaryNarrative.textContent=`${c.better?'What feels better: '+c.better+'. ':''}${c.limited?'What still feels limited: '+c.limited+'. ':''}Pain is currently ${c.pain}/10 and overall improvement is estimated at ${c.improvement}%.`;}
openSummary.addEventListener('click',()=>{updateSummaryModal();summaryModal.classList.add('open')});document.querySelector('.close-summary').addEventListener('click',()=>summaryModal.classList.remove('open'));summaryModal.addEventListener('click',e=>{if(e.target===summaryModal)summaryModal.classList.remove('open')});
function summaryText(){const c=latestCheckin;return `Stride progress summary: pain ${c.pain}/10; overall improvement ${c.improvement}%; exercise consistency ${c.consistency.toLowerCase()}; morning stiffness ${c.morning.toLowerCase()}; walking tolerance ${c.walking.toLowerCase()}; shoe comfort ${c.shoes.toLowerCase()}; flare-ups ${c.flare.toLowerCase()}. ${c.better?'Better: '+c.better+'. ':''}${c.limited?'Still limited: '+c.limited+'.':''}`}
copyProgressSummary.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(summaryText());copyProgressSummary.textContent='Copied';setTimeout(()=>copyProgressSummary.textContent='Copy Summary',1200)}catch(e){alert(summaryText())}});shareProgressSummary.addEventListener('click',async()=>{const t=summaryText();if(navigator.share){try{await navigator.share({title:'Stride Progress Summary',text:t})}catch(e){}}else{try{await navigator.clipboard.writeText(t);alert('Summary copied.')}catch(e){alert(t)}}});

const journeyStages=[
{name:'Getting Started',weeks:'Weeks 1–4',description:'Your initial assessment and initial adjustment are complete. Early FMT sessions focus on loosening restrictions and helping the foot and ankle joints move more freely.',fmt:'Loosen restrictions and begin getting the foot and ankle joints moving.',patient:'Complete prescribed exercises, attend FMT consistently, and notice patterns in symptoms and activity.',milestone:'Initial assessment and initial adjustment completed.',note:'You have taken the first important step. Focus on consistency and noticing how your movement responds.'},
{name:'Foundation Phase',weeks:'Weeks 5–8',description:'After your progress review, FMT usually becomes less frequent while the changes made during the first month are reinforced.',fmt:'Maintain changes, keep joints mobile, introduce strengthening, and target surrounding structures.',patient:'Continue prescribed exercises and stay consistent with appointments and healthy movement habits.',milestone:'Progress Review completed around Week 5 and your plan updated.',note:'Keep going — the changes you are building now support stronger, more comfortable movement.'},
{name:'Maintenance Phase',weeks:'Weeks 9–13',description:'Regular FMT sessions are gradually reduced while your podiatrist checks that movement is holding and there is no regression.',fmt:'Wean from regular FMT, monitor for regression, and build self-management tools.',patient:'Keep up prescribed exercises, use your self-management tools, and attend planned reviews.',milestone:'90-day review completed and long-term recommendations confirmed.',note:'You are building the confidence and tools to maintain your progress more independently.'},
{name:'Ongoing Support',weeks:'After 90 days',description:'The structured phase is complete and you are ready to self-manage, with support available when you need it.',fmt:'Periodic review of movement, symptoms, exercises, and any new concerns.',patient:'Continue exercises and arrange a review if symptoms change. Many patients prefer an FMT check every 6–12 months.',milestone:'Maintaining progress independently without regular sessions.',note:'Keep using the tools that help you move well, with periodic support when needed.'}
];
let currentStage=Math.min(3,Math.max(0,Number(localStorage.getItem('strideJourneyStage')||0)));
function renderJourneyPhases(){const phaseList=document.getElementById('journeyPhaseList');if(!phaseList)return;phaseList.innerHTML=journeyStages.map((stage,i)=>{const selected=i===currentStage;return `<article class="phase-card ${selected?'current open':''}" data-stage="${i}"><button class="phase-header" type="button"><span class="phase-icon">${selected?icons.check:String(i+1)}</span><span><span class="phase-weeks">${stage.weeks}</span><span class="phase-title">${stage.name}</span></span><span class="phase-status">${selected?'Current':'Select'}</span></button><div class="phase-details"><p>${stage.description}</p><div class="detail-row"><strong>FMT focus</strong><span>${stage.fmt}</span></div><div class="detail-row"><strong>Your focus</strong><span>${stage.patient}</span></div><div class="detail-row"><strong>Milestone</strong><span>${stage.milestone}</span></div><button class="btn secondary phase-select" type="button" data-select-stage="${i}">${selected?'Current phase':'Set as current phase'}</button></div></article>`}).join('');phaseList.querySelectorAll('.phase-header').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.phase-card').classList.toggle('open')));phaseList.querySelectorAll('[data-select-stage]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();setJourneyStage(Number(btn.dataset.selectStage));}))}
function setJourneyStage(index){currentStage=Math.min(3,Math.max(0,Number(index)||0));localStorage.setItem('strideJourneyStage',String(currentStage));const s=journeyStages[currentStage];const homeStageLabel=document.getElementById('homeStageLabel');if(homeStageLabel)homeStageLabel.textContent=s.name;const homeStageNote=document.getElementById('homeStageNote');if(homeStageNote)homeStageNote.textContent=s.note;const onboardStageEl=document.getElementById('onboardStage');if(onboardStageEl)onboardStageEl.value=String(currentStage);renderJourneyPhases()}
setJourneyStage(currentStage);

let slideIndex=0;
let onboardingPain=null;
const onboardingEl=document.getElementById('onboarding');
const slidesEl=document.getElementById('slides');
const startOnboardingButton=document.getElementById('startOnboarding');
const finishOnboardingButton=document.getElementById('finishOnboarding');
function moveSlide(i){slideIndex=i;if(slidesEl)slidesEl.style.transform=`translateX(-${i*100}%)`}
function saveOnboardingDetails(){const name=(document.getElementById('onboardName')?.value||'').trim();const goal=(document.getElementById('onboardGoal')?.value||'').trim();const stage=Number(document.getElementById('onboardStage')?.value||0);if(name){localStorage.setItem('strideProfilePreferredName',name);localStorage.setItem('strideProfileName',name)}localStorage.setItem('strideJourneyStage',String(stage));if(goal)localStorage.setItem('strideGoal',goal);if(onboardingPain!==null)localStorage.setItem('strideInitialPain',String(onboardingPain));setJourneyStage(stage);loadOnboardingData();updateHomeGreeting();}
function completeOnboarding(){saveOnboardingDetails();localStorage.setItem('strideOnboardingComplete','true');onboardingEl?.classList.add('hidden')}
if(localStorage.getItem('strideOnboardingComplete')==='true'){onboardingEl?.classList.add('hidden')}
if(startOnboardingButton)startOnboardingButton.addEventListener('click',()=>moveSlide(1));
const continueToSetupButton=document.getElementById('continueToSetup');if(continueToSetupButton)continueToSetupButton.addEventListener('click',()=>moveSlide(2));
const skipPatientIntroButton=document.getElementById('skipPatientIntro');if(skipPatientIntroButton)skipPatientIntroButton.addEventListener('click',()=>moveSlide(2));
document.querySelectorAll('.onboard-next').forEach(b=>b.addEventListener('click',()=>{saveOnboardingDetails();moveSlide(Number(b.dataset.nextStep))}));
document.querySelectorAll('[data-back-step]').forEach(b=>b.addEventListener('click',()=>moveSlide(Number(b.dataset.backStep))));
document.querySelectorAll('[data-onboard-intent]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-onboard-intent]').forEach(x=>x.classList.toggle('selected',x===b));localStorage.setItem('strideOnboardingIntent',b.dataset.onboardIntent)}));
document.querySelectorAll('[data-onboard-pain]').forEach(b=>b.addEventListener('click',()=>{onboardingPain=Number(b.dataset.onboardPain);document.querySelectorAll('[data-onboard-pain]').forEach(x=>x.classList.toggle('selected',x===b));onboardPainSelected.textContent=`Selected: ${onboardingPain}/10`}));
document.getElementById('onboardScanQr').addEventListener('click',()=>{document.getElementById('scanModal').classList.add('open')});
document.getElementById('onboardCreateAccount').addEventListener('click',()=>{saveOnboardingDetails();openAccountModal('create')});
if(finishOnboardingButton)finishOnboardingButton.addEventListener('click',completeOnboarding);

const accountModal=document.getElementById('accountModal');const resetPasswordModal=document.getElementById('resetPasswordModal');const authFeedback=document.getElementById('authFeedback');
function openAccountModal(tab='signin'){accountModal.classList.add('open');setAuthTab(tab)}function closeAccountModal(){accountModal.classList.remove('open');authFeedback.textContent='';authFeedback.className='auth-feedback'}
function setAuthTab(tab){document.querySelectorAll('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));signinPanel.classList.toggle('active',tab==='signin');createPanel.classList.toggle('active',tab==='create');accountModalTitle.textContent=tab==='signin'?'Sign in to Stride':'Create your Stride account';authFeedback.textContent='';authFeedback.className='auth-feedback'}
const existingAccountButton=document.getElementById('accountLink');if(existingAccountButton){existingAccountButton.addEventListener('click',()=>openAccountModal('signin'))}document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>setAuthTab(b.dataset.authTab)));document.querySelector('.close-account').addEventListener('click',closeAccountModal);accountModal.addEventListener('click',e=>{if(e.target===accountModal)closeAccountModal()});
function updateAccountStatus(){const email=localStorage.getItem('strideAccountEmail');const status=document.getElementById('accountStatus');if(status)status.textContent=email?`Signed in as ${email}`:'No account is currently signed in on this device.'}
function validPassword(value){return value.length>=8}
createAccountButton.addEventListener('click',()=>{const first=createFirstName.value.trim(),last=createLastName.value.trim(),preferred=createPreferredName.value.trim(),email=createEmail.value.trim().toLowerCase(),password=createPassword.value,confirm=createPasswordConfirm.value;if(!first||!last||!email){authFeedback.textContent='Please enter your first name, last name and email.';authFeedback.className='auth-feedback error';return}if(!validPassword(password)){authFeedback.textContent='Password must be at least 8 characters.';authFeedback.className='auth-feedback error';return}if(password!==confirm){authFeedback.textContent='Passwords do not match.';authFeedback.className='auth-feedback error';return}localStorage.setItem('strideAccountEmail',email);localStorage.setItem('strideAccountPassword',password);localStorage.setItem('strideProfileFirstName',first);localStorage.setItem('strideProfileLastName',last);localStorage.setItem('strideProfilePreferredName',preferred);localStorage.setItem('strideProfileName',preferred||first);localStorage.setItem('strideProfileEmail',email);localStorage.setItem('strideOnboardingComplete','true');localStorage.setItem('strideSignedIn','true');loadProfile();updateHomeGreeting();updateAccountStatus();authFeedback.textContent='Account created and signed in.';authFeedback.className='auth-feedback success';setTimeout(()=>{closeAccountModal();onboardingEl?.classList.add('hidden')},700)});
signinButton.addEventListener('click',()=>{const email=signinEmail.value.trim().toLowerCase(),password=signinPassword.value;const storedEmail=(localStorage.getItem('strideAccountEmail')||'').toLowerCase(),storedPassword=localStorage.getItem('strideAccountPassword')||'';if(!email||!password){authFeedback.textContent='Please enter your email and password.';authFeedback.className='auth-feedback error';return}if(!storedEmail){authFeedback.textContent='No Stride account has been created on this device yet. Choose Create account to set one up.';authFeedback.className='auth-feedback error';return}if(email!==storedEmail||password!==storedPassword){authFeedback.textContent='Email or password is incorrect.';authFeedback.className='auth-feedback error';return}localStorage.setItem('strideOnboardingComplete','true');localStorage.setItem('strideSignedIn','true');authFeedback.textContent='Signed in successfully.';authFeedback.className='auth-feedback success';updateAccountStatus();setTimeout(()=>{closeAccountModal();if(window.onboardingEl){onboardingEl.classList.add('hidden')}else{document.getElementById('onboarding')?.classList.add('hidden')}showScreen('home')},500)});signinPassword.addEventListener('keydown',e=>{if(e.key==='Enter')signinButton.click()});
updateAccountStatus();
resetPasswordButton.addEventListener('click',()=>{resetPasswordModal.classList.add('open');resetPasswordFeedback.textContent='';newPassword.value='';newPasswordConfirm.value=''});document.querySelector('.close-reset-password').addEventListener('click',()=>resetPasswordModal.classList.remove('open'));resetPasswordModal.addEventListener('click',e=>{if(e.target===resetPasswordModal)resetPasswordModal.classList.remove('open')});saveNewPassword.addEventListener('click',()=>{if(!localStorage.getItem('strideAccountEmail')){resetPasswordFeedback.textContent='Create an account before setting a password.';resetPasswordFeedback.className='auth-feedback error';return}if(!validPassword(newPassword.value)){resetPasswordFeedback.textContent='Password must be at least 8 characters.';resetPasswordFeedback.className='auth-feedback error';return}if(newPassword.value!==newPasswordConfirm.value){resetPasswordFeedback.textContent='Passwords do not match.';resetPasswordFeedback.className='auth-feedback error';return}localStorage.setItem('strideAccountPassword',newPassword.value);resetPasswordFeedback.textContent='Password updated.';resetPasswordFeedback.className='auth-feedback success';setTimeout(()=>resetPasswordModal.classList.remove('open'),700)});


const signOutButton=document.getElementById('signOutButton');if(signOutButton){signOutButton.addEventListener('click',()=>{localStorage.removeItem('strideSignedIn');showScreen('home');openAccountModal('signin');authFeedback.textContent='You have been signed out.';authFeedback.className='auth-feedback success';updateAccountStatus()})}

const scanModal=document.getElementById('scanModal');
const scannerVideo=document.getElementById('scannerVideo');
const scanStatusText=document.getElementById('scanStatusText');
const scanStatus=document.getElementById('scanStatus');
const manualCodeInput=document.getElementById('manualCodeInput');
let scanStream=null, scanTimer=null, barcodeDetector=null;
function openScanModal(){scanModal.classList.add('open')}
function closeScanModal(){stopScanner();scanModal.classList.remove('open')}
document.getElementById('openScanner').addEventListener('click',openScanModal);
document.querySelector('.close-scan').addEventListener('click',closeScanModal);
scanModal.addEventListener('click',e=>{if(e.target===scanModal)closeScanModal()});
function normalizeCode(raw=''){return raw.toLowerCase().trim().replace(/^resource:/,'').replace(/^stride:/,'')}
function completeScan(raw){const code=normalizeCode(raw);const item=resources.find(r=>r.id===code);if(!item){scanStatusText.textContent='Code not recognised. Try another QR code or enter a demo code manually.';return}saved.add(item.id);localStorage.setItem('stridePrescribedResources',JSON.stringify([...saved]));renderMyResources();scanStatus.textContent=`Added ${item.title} to My Resources.`;scanStatusText.textContent=`Added ${item.title}. You can scan another code or close this window.`;manualCodeInput.value='';stopScanner()}
async function startScanner(){scanStatusText.textContent='Starting camera…';if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){scanStatusText.textContent='Camera scanning is not supported on this device. Enter a code manually below.';return}try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});scannerVideo.srcObject=scanStream;await scannerVideo.play();if('BarcodeDetector' in window){barcodeDetector=new BarcodeDetector({formats:['qr_code']});scanStatusText.textContent='Point your camera at a QR code.';scanTimer=setInterval(async()=>{try{const codes=await barcodeDetector.detect(scannerVideo);if(codes&&codes.length){completeScan(codes[0].rawValue||'')}}catch(err){}},700)}else{scanStatusText.textContent='Live QR detection is not supported here. You can still enter the code manually below.'}}catch(err){scanStatusText.textContent='Camera access was unavailable. Please allow camera access or enter the code manually.'}}
function stopScanner(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}if(scannerVideo.srcObject)scannerVideo.srcObject=null}
document.getElementById('startScannerBtn').addEventListener('click',startScanner);
document.getElementById('stopScannerBtn').addEventListener('click',()=>{stopScanner();scanStatusText.textContent='Scanner stopped.'});
document.getElementById('addManualCode').addEventListener('click',()=>completeScan(manualCodeInput.value));
manualCodeInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();completeScan(manualCodeInput.value)}});

const motivationMessages=[
  {title:'Your feet are doing important work. Keep going.',sub:'Small steps add up — your progress is worth celebrating.'},
  {title:'Every exercise is a step toward moving better.',sub:'Consistency today helps build confidence tomorrow.'},
  {title:'Progress does not have to be perfect to be meaningful.',sub:'Keep showing up for the small habits that support your movement.'},
  {title:'Your body is learning a better way to move.',sub:'Give it time, repetition and the support it needs.'},
  {title:'A little progress today can make a big difference tomorrow.',sub:'Complete your plan and notice the small changes along the way.'},
  {title:'You are building better movement, one small win at a time.',sub:'Keep your exercises consistent and track how you are feeling.'},
  {title:'Movement improves through patience and practice.',sub:'Stay consistent and let your progress build gradually.'},
  {title:'Keep going — the work you are doing matters.',sub:'Each completed exercise supports your longer-term goals.'},
  {title:'Today is another chance to support your progress.',sub:'Focus on what you can do and celebrate the effort.'},
  {title:'Strong progress starts with steady habits.',sub:'Keep attending, keep moving and keep noticing what changes.'},
  {title:'Your future movement is shaped by what you do today.',sub:'A few focused minutes can help keep you moving forward.'},
  {title:'Be patient with your progress and proud of your consistency.',sub:'Your podiatrist can use your updates to keep your plan on track.'}
];
const motivationText=document.getElementById('motivationText');
const motivationSubtext=document.getElementById('motivationSubtext');
const motivationBanner=document.getElementById('motivationBanner');
const dismissMotivation=document.getElementById('dismissMotivation');
const today=new Date();const dayKey=Math.floor(Date.UTC(today.getFullYear(),today.getMonth(),today.getDate())/86400000);const todaysMessage=motivationMessages[dayKey%motivationMessages.length];
if(motivationText&&motivationSubtext){motivationText.textContent=todaysMessage.title;motivationSubtext.textContent=todaysMessage.sub;}
if(dismissMotivation){dismissMotivation.addEventListener('click',()=>motivationBanner.classList.add('hidden'));}


function updateHomeGreeting(){
  const hour=new Date().getHours();
  const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
  const savedName=(localStorage.getItem('strideProfilePreferredName')||localStorage.getItem('strideProfileFirstName')||localStorage.getItem('strideProfileName')||'Alex').trim()||'Alex';
  const firstName=savedName.split(/\s+/)[0];
  const greetingEl=document.getElementById('timeGreeting');
  const nameEl=document.getElementById('homeFirstName');
  if(greetingEl&&nameEl){greetingEl.childNodes[0].nodeValue=greeting+',';nameEl.textContent=firstName;}
}
updateHomeGreeting();
function loadOnboardingData(){const goal=localStorage.getItem('strideGoal')||'Move more comfortably and confidently.';const pain=localStorage.getItem('strideInitialPain');['progressGoalText','journeyGoalText'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=goal});const painEl=document.getElementById('progressInitialPain');if(painEl)painEl.textContent=pain!==null?`${pain}/10`:'Not recorded';const name=localStorage.getItem('strideProfilePreferredName')||localStorage.getItem('strideProfileName')||'';const onboardName=document.getElementById('onboardName');if(onboardName&&!onboardName.value)onboardName.value=name;const onboardGoal=document.getElementById('onboardGoal');if(onboardGoal&&!onboardGoal.value&&localStorage.getItem('strideGoal'))onboardGoal.value=localStorage.getItem('strideGoal');const onboardStage=document.getElementById('onboardStage');if(onboardStage)onboardStage.value=localStorage.getItem('strideJourneyStage')||'0';}
loadOnboardingData();
const profileFirstName=document.getElementById('profileFirstName');const profileLastName=document.getElementById('profileLastName');const profilePreferredName=document.getElementById('profilePreferredName');const profileEmail=document.getElementById('profileEmail');
function loadProfile(){if(!profileFirstName)return;profileFirstName.value=localStorage.getItem('strideProfileFirstName')||'';profileLastName.value=localStorage.getItem('strideProfileLastName')||'';profilePreferredName.value=localStorage.getItem('strideProfilePreferredName')||localStorage.getItem('strideProfileName')||'Alex';profileEmail.value=localStorage.getItem('strideProfileEmail')||'';}
function saveProfileDetails(){localStorage.setItem('strideProfileFirstName',profileFirstName.value.trim());localStorage.setItem('strideProfileLastName',profileLastName.value.trim());localStorage.setItem('strideProfilePreferredName',profilePreferredName.value.trim());localStorage.setItem('strideProfileName',profilePreferredName.value.trim()||profileFirstName.value.trim()||'Alex');localStorage.setItem('strideProfileEmail',profileEmail.value.trim());document.getElementById('profileFeedback').textContent='Profile saved on this device.';updateHomeGreeting();updateAccountStatus();}
loadProfile();if(document.getElementById('saveProfile'))document.getElementById('saveProfile').addEventListener('click',saveProfileDetails);
document.querySelectorAll('.toggle[data-setting]').forEach(toggle=>{const key='strideSetting-'+toggle.dataset.setting;const stored=localStorage.getItem(key);if(stored!==null)toggle.classList.toggle('on',stored==='true');toggle.addEventListener('click',()=>{toggle.classList.toggle('on');localStorage.setItem(key,toggle.classList.contains('on'));});});
const clinicUpdatesToggle=document.getElementById('clinicUpdatesToggle');const exerciseRemindersToggle=document.getElementById('exerciseRemindersToggle');const progressRemindersToggle=document.getElementById('progressRemindersToggle');const exerciseReminderOptions=document.getElementById('exerciseReminderOptions');const progressReminderOptions=document.getElementById('progressReminderOptions');const exerciseTimeOne=document.getElementById('exerciseTimeOne');const exerciseTimeTwo=document.getElementById('exerciseTimeTwo');const exerciseTimeTwoField=document.getElementById('exerciseTimeTwoField');const exerciseTimeOneLabel=document.getElementById('exerciseTimeOneLabel');const progressReminderTime=document.getElementById('progressReminderTime');const notificationFeedback=document.getElementById('notificationFeedback');
if(clinicUpdatesToggle){if(localStorage.getItem('strideSetting-clinic-updates')===null){localStorage.setItem('strideSetting-clinic-updates','true');clinicUpdatesToggle.classList.add('on')}}
function showNotificationSaved(){if(!notificationFeedback)return;notificationFeedback.textContent='Notification preferences saved on this device.';clearTimeout(window.__notificationSavedTimer);window.__notificationSavedTimer=setTimeout(()=>notificationFeedback.textContent='',1800)}
function syncNotificationPanels(){if(exerciseReminderOptions)exerciseReminderOptions.classList.toggle('hidden',!exerciseRemindersToggle.classList.contains('on'));if(progressReminderOptions)progressReminderOptions.classList.toggle('hidden',!progressRemindersToggle.classList.contains('on'))}
[clinicUpdatesToggle,exerciseRemindersToggle,progressRemindersToggle].filter(Boolean).forEach(t=>t.addEventListener('click',()=>{syncNotificationPanels();showNotificationSaved()}));
let reminderCount=Number(localStorage.getItem('strideExerciseReminderCount')||'1');
function applyReminderCount(count){reminderCount=count;document.querySelectorAll('[data-reminder-count]').forEach(b=>b.classList.toggle('active',Number(b.dataset.reminderCount)===count));if(exerciseTimeTwoField)exerciseTimeTwoField.classList.toggle('hidden',count!==2);if(exerciseTimeOneLabel)exerciseTimeOneLabel.textContent=count===2?'Morning reminder':'Reminder time';localStorage.setItem('strideExerciseReminderCount',String(count))}
document.querySelectorAll('[data-reminder-count]').forEach(b=>b.addEventListener('click',()=>{applyReminderCount(Number(b.dataset.reminderCount));showNotificationSaved()}));
if(exerciseTimeOne){exerciseTimeOne.value=localStorage.getItem('strideExerciseTimeOne')||'08:00';exerciseTimeOne.addEventListener('change',()=>{localStorage.setItem('strideExerciseTimeOne',exerciseTimeOne.value);showNotificationSaved()})}
if(exerciseTimeTwo){exerciseTimeTwo.value=localStorage.getItem('strideExerciseTimeTwo')||'19:00';exerciseTimeTwo.addEventListener('change',()=>{localStorage.setItem('strideExerciseTimeTwo',exerciseTimeTwo.value);showNotificationSaved()})}
if(progressReminderTime){progressReminderTime.value=localStorage.getItem('strideProgressReminderTime')||'18:00';progressReminderTime.addEventListener('change',()=>{localStorage.setItem('strideProgressReminderTime',progressReminderTime.value);showNotificationSaved()})}
applyReminderCount(reminderCount);syncNotificationPanels();
document.querySelectorAll('.text-size-button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.text-size-button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.documentElement.style.fontSize=btn.dataset.size==='large'?'18px':btn.dataset.size==='small'?'14px':'16px';localStorage.setItem('strideTextSize',btn.dataset.size);}));
const contrastToggle=document.getElementById('contrastToggle');if(contrastToggle)contrastToggle.addEventListener('click',()=>{contrastToggle.classList.toggle('on');document.documentElement.style.filter=contrastToggle.classList.contains('on')?'contrast(1.15)':'';});
const motionToggle=document.getElementById('motionToggle');if(motionToggle)motionToggle.addEventListener('click',()=>{motionToggle.classList.toggle('on');document.documentElement.style.setProperty('--motion',motionToggle.classList.contains('on')?'0s':'');document.querySelectorAll('.splash-bg img,.splash-logo,.splash-bottom h1,.splash-bottom .btn,.splash-link').forEach(el=>el.style.animation=motionToggle.classList.contains('on')?'none':'');});
const shopUrl='https://advancedpodiatry.co.nz/team-2-2/';
const shopProducts=[
{name:'Budin Toe Splint – Single or Double Loop',price:'$23.00–$27.00',category:'support',categoryLabel:'Toe support',icon:'support',url:'https://advancedpodiatry.co.nz/product/budin-splint-single/'},
{name:'Formthotics Dual Density Prefabricated Orthotic',price:'$85.00',category:'support',categoryLabel:'Orthotic support',icon:'orthotic',url:'https://advancedpodiatry.co.nz/product/formthotics-dual-density-y1/'},
{name:'Formthotics Heel Raisers – 4 mm',price:'$5.00',category:'support',categoryLabel:'Heel support',icon:'orthotic',url:'https://advancedpodiatry.co.nz/product/heel-raiser-low-4mm-single-l/'},
{name:'Formthotics Self-Adhesive Metatarsal Domes',price:'$5.00',category:'support',categoryLabel:'Forefoot support',icon:'orthotic',url:'https://advancedpodiatry.co.nz/product/metatarsal-dome-single-m/'},
{name:'HikersWool Midi Pack – 18 g',price:'$15.00',category:'foot-care',categoryLabel:'Blister care',icon:'care',url:'https://advancedpodiatry.co.nz/product/hikerswool-midi-pack/'},
{name:'Medium Strength Premium Resistance Band – 1.5 m',price:'$8.00',category:'exercise',categoryLabel:'Exercise',icon:'support',url:'https://advancedpodiatry.co.nz/product/allcare-premium-resistance-exercise-band-1-5m/'},
{name:'That’s It Anti Chafe Gel – 25 ml',price:'$23.90',category:'foot-care',categoryLabel:'Skin protection',icon:'care',url:'https://advancedpodiatry.co.nz/product/thats-it-anti-chafe-gel-25ml/'},
{name:'That’s It Blister Stop Wool – 10 g',price:'$18.90',category:'foot-care',categoryLabel:'Blister care',icon:'care',url:'https://advancedpodiatry.co.nz/product/thats-it-blister-stop-wool-10g/'},
{name:'That’s It Hot Rub – 80 ml',price:'$35.90',category:'foot-care',categoryLabel:'Muscle care',icon:'care',url:'https://advancedpodiatry.co.nz/product/thats-it-hot-rub-80ml/'}
];
let activeShopFilter='all';
const shopProductList=document.getElementById('shopProductList');
function renderShopProducts(){if(!shopProductList)return;const query=(document.getElementById('shopSearch')?.value||'').toLowerCase().trim();const filtered=shopProducts.filter(product=>(activeShopFilter==='all'||product.category===activeShopFilter)&&(!query||product.name.toLowerCase().includes(query)||product.categoryLabel.toLowerCase().includes(query)));document.getElementById('shopResultCount').textContent=`Showing ${filtered.length} of ${shopProducts.length} featured products`;shopProductList.innerHTML=filtered.length?filtered.map(product=>`<a class="store-card" href="${product.url}" target="_blank" rel="noopener"><div class="store-thumb"><span class="store-category">${product.categoryLabel}</span>${icons[product.icon]||icons.cart}</div><div class="store-body"><h3>${product.name}</h3><div class="store-price">${product.price}</div><div class="store-link"><span>View product</span><span>›</span></div></div></a>`).join(''):'<div class="shop-empty">No products match this search.</div>'}
document.querySelectorAll('[data-shop-filter]').forEach(button=>button.addEventListener('click',()=>{activeShopFilter=button.dataset.shopFilter;document.querySelectorAll('[data-shop-filter]').forEach(item=>item.classList.toggle('active',item===button));renderShopProducts()}));
const shopSearch=document.getElementById('shopSearch');if(shopSearch)shopSearch.addEventListener('input',renderShopProducts);
renderShopProducts();



let selectedFeedbackType='Bug report';
document.querySelectorAll('.feedback-type').forEach(button=>button.addEventListener('click',()=>{selectedFeedbackType=button.dataset.feedbackType;document.querySelectorAll('.feedback-type').forEach(item=>item.classList.toggle('active',item===button))}));
const sendFeedbackButton=document.getElementById('sendFeedback');
if(sendFeedbackButton){sendFeedbackButton.addEventListener('click',()=>{const subject=document.getElementById('feedbackSubject').value.trim();const message=document.getElementById('feedbackMessage').value.trim();const contact=document.getElementById('feedbackEmail').value.trim();if(!subject||!message){alert('Please add a subject and some details before sending.');return;}const profileName=localStorage.getItem('strideProfilePreferredName')||localStorage.getItem('strideProfileFirstName')||'';const body=[`Feedback type: ${selectedFeedbackType}`,`Name: ${profileName||'Not provided'}`,`Contact email: ${contact||'Not provided'}`,'',message,'','App: Stride prototype','Device: '+navigator.userAgent].join('\n');const mailto=`mailto:info@advancedpodiatry.co.nz?subject=${encodeURIComponent('[Stride] '+selectedFeedbackType+' - '+subject)}&body=${encodeURIComponent(body)}`;document.getElementById('feedbackSuccess').classList.add('show');window.location.href=mailto;});}

const languageStrings={
 en:{home:'Home',resources:'Resources',progress:'Progress',journey:'Journey',more:'More',getStarted:'Get Started',account:'I already have an account',language:'Language',appLanguage:'App language',languageNote:'This changes the app navigation and key interface text. Patient-entered notes remain exactly as written.',welcome:'Ready to move better with Stride?',exercisesTitle:'Exercises',exercisesIntro:'Your prescribed exercises and the full Stride resource library.',prescribed:'Prescribed',library:'Library',progressTitle:'Progress',journeyTitle:'My Journey',moreTitle:'More',profile:'Profile',notifications:'Notification Preferences',accessibility:'Accessibility',about:'About Stride',privacy:'Privacy Policy',terms:'Terms of Use',accessibilityTitle:'Accessibility',accessibilityIntro:'Adjust Stride to make it easier to use.',textSize:'Text size',small:'Small',standard:'Standard',large:'Large',highContrast:'High contrast',reduceAnimation:'Reduce animation'},
 mi:{home:'Kāinga',resources:'Rauemi',progress:'Te Anga Whakamua',journey:'Tō Haerenga',more:'Ētahi Atu',getStarted:'Tīmata',account:'He pūkete kē tāku',language:'Reo',appLanguage:'Te reo o te taupānga',languageNote:'Ka huri tēnei i ngā kupu matua me te whakatere o te taupānga. Ka noho tonu ngā kōrero a te tūroro ki te reo i tuhia ai.',welcome:'Kua reri ki te neke pai ake me Stride?',exercisesTitle:'Ngā Mahi Korikori',exercisesIntro:'Ō mahi kua whakaritea me te whare pukapuka rauemi Stride.',prescribed:'Kua whakaritea',library:'Whare Pukapuka',progressTitle:'Te Anga Whakamua',journeyTitle:'Tō Haerenga',moreTitle:'Ētahi Atu',profile:'Kōtaha',notifications:'Ngā Manakohanga Whakamōhiotanga',accessibility:'Urunga',about:'Mō Stride',privacy:'Kaupapahere Tūmataiti',terms:'Ngā Here Whakamahi',accessibilityTitle:'Urunga',accessibilityIntro:'Whakaritea a Stride kia māmā ake te whakamahi.',textSize:'Rahi kupu',small:'Iti',standard:'Paerewa',large:'Nui',highContrast:'Rerekētanga teitei',reduceAnimation:'Whakaitihia te nekehanga'},
 zh:{home:'首页',resources:'资源',progress:'进度',journey:'旅程',more:'更多',getStarted:'开始',account:'我已有账户',language:'语言',appLanguage:'应用语言',languageNote:'这会更改应用的导航和主要界面文字。患者输入的记录会保持原样。',welcome:'准备好与 Stride 一起更好地活动了吗？',exercisesTitle:'练习',exercisesIntro:'您的处方练习和完整的 Stride 资源库。',prescribed:'已处方',library:'资料库',progressTitle:'进度',journeyTitle:'我的旅程',moreTitle:'更多',profile:'个人资料',notifications:'通知偏好',accessibility:'辅助功能',about:'关于 Stride',privacy:'隐私政策',terms:'使用条款',accessibilityTitle:'辅助功能',accessibilityIntro:'调整 Stride，使其更易于使用。',textSize:'文字大小',small:'小',standard:'标准',large:'大',highContrast:'高对比度',reduceAnimation:'减少动画'},
 sm:{home:'Itulau Autū',resources:'Punaoa',progress:'Alualu i Luma',journey:'Lau Malaga',more:'Isi Mea',getStarted:'Amata',account:'Ua iai laʻu teugatupe',language:'Gagana',appLanguage:'Gagana o le app',languageNote:'E suia ai le faiga o le app ma upu autū. O faamatalaga e tusia e le tagata maʻi e tumau pea e pei ona tusia.',welcome:'Ua e sauni e gaoioi lelei atu ma Stride?',exercisesTitle:'Faamalositino',exercisesIntro:'Au faamalositino ua faatonuina ma le faletusi atoa o punaoa a Stride.',prescribed:'Ua faatonuina',library:'Faletusi',progressTitle:'Alualu i Luma',journeyTitle:'Lau Malaga',moreTitle:'Isi Mea',profile:'Talaaga',notifications:'Filifiliga o Faasilasilaga',accessibility:'Faigofie ona Faaaoga',about:'E uiga ia Stride',privacy:'Tulafono Faalilolilo',terms:'Aiaiga o le Faaaogāina',accessibilityTitle:'Faigofie ona Faaaoga',accessibilityIntro:'Fetuunai Stride ina ia faigofie ona faaaoga.',textSize:'Tele o Tusitusiga',small:'Laiti',standard:'Masani',large:'Tele',highContrast:'Maualuga le eseesega',reduceAnimation:'Faaitiitia gaioiga'},
 hi:{home:'होम',resources:'संसाधन',progress:'प्रगति',journey:'यात्रा',more:'और',getStarted:'शुरू करें',account:'मेरे पास पहले से खाता है',language:'भाषा',appLanguage:'ऐप की भाषा',languageNote:'यह ऐप के नेविगेशन और मुख्य इंटरफ़ेस के शब्दों को बदलता है। मरीज द्वारा लिखे गए नोट उसी रूप में रहेंगे।',welcome:'Stride के साथ बेहतर चलने के लिए तैयार हैं?',exercisesTitle:'व्यायाम',exercisesIntro:'आपके निर्धारित व्यायाम और पूरा Stride संसाधन पुस्तकालय।',prescribed:'निर्धारित',library:'पुस्तकालय',progressTitle:'प्रगति',journeyTitle:'मेरी यात्रा',moreTitle:'और',profile:'प्रोफ़ाइल',notifications:'सूचना प्राथमिकताएँ',accessibility:'सुलभता',about:'Stride के बारे में',privacy:'गोपनीयता नीति',terms:'उपयोग की शर्तें',accessibilityTitle:'सुलभता',accessibilityIntro:'Stride को अपने लिए उपयोग में आसान बनाएं।',textSize:'पाठ का आकार',small:'छोटा',standard:'मानक',large:'बड़ा',highContrast:'उच्च कंट्रास्ट',reduceAnimation:'एनीमेशन कम करें'},
 es:{home:'Inicio',resources:'Recursos',progress:'Progreso',journey:'Recorrido',more:'Más',getStarted:'Comenzar',account:'Ya tengo una cuenta',language:'Idioma',appLanguage:'Idioma de la aplicación',languageNote:'Esto cambia la navegación y los textos principales de la aplicación. Las notas introducidas por el paciente se mantienen tal como fueron escritas.',welcome:'¿Listo para moverte mejor con Stride?',exercisesTitle:'Ejercicios',exercisesIntro:'Tus ejercicios prescritos y la biblioteca completa de recursos de Stride.',prescribed:'Prescritos',library:'Biblioteca',progressTitle:'Progreso',journeyTitle:'Mi recorrido',moreTitle:'Más',profile:'Perfil',notifications:'Preferencias de notificaciones',accessibility:'Accesibilidad',about:'Acerca de Stride',privacy:'Política de privacidad',terms:'Condiciones de uso',accessibilityTitle:'Accesibilidad',accessibilityIntro:'Ajusta Stride para que sea más fácil de usar.',textSize:'Tamaño del texto',small:'Pequeño',standard:'Estándar',large:'Grande',highContrast:'Alto contraste',reduceAnimation:'Reducir animación'}
};
function applyLanguage(code){const s=languageStrings[code]||languageStrings.en;document.documentElement.lang=code==='zh'?'zh-CN':code==='hi'?'hi-IN':code==='es'?'es':code;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(s[k])el.textContent=s[k]});const w=document.getElementById('welcomeTitle');if(w)w.textContent=s.welcome;const a=document.getElementById('accountLink');if(a)a.textContent=s.account;const h=document.getElementById('languageHeading');if(h)h.textContent=s.language;const l=document.getElementById('languageLabel');if(l)l.textContent=s.appLanguage;const n=document.getElementById('languageNote');if(n)n.textContent=s.languageNote;localStorage.setItem('strideLanguage',code);const sel=document.getElementById('languageSelect');if(sel)sel.value=code}
const languageSelect=document.getElementById('languageSelect');if(languageSelect){const savedLanguage=localStorage.getItem('strideLanguage')||'en';languageSelect.value=savedLanguage;applyLanguage(savedLanguage);languageSelect.addEventListener('change',()=>applyLanguage(languageSelect.value));}

renderMyResources();renderLibrary();bindResourceButtons();
